/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetodoNoroeste;

import Menu.mains;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lipiri
 */
public class Esquina extends javax.swing.JFrame {
    mains menu = new mains();
    /**
     * Creates new form Esquina
     */
    public Esquina() {
        initComponents();
    }
    public double []comprobar(double m[][],int o,int d){
        double v[]=new double[4];
        double so=0,sd=0;
        for(int i=0;i<o;i++){
            so=so+m[i][d-1];
        }
        for(int i=0;i<d;i++){
            sd=sd+m[o-1][i];
        }
        if(sd!=so){
            //145  45
            if(sd>so){
                o=o+1;//3
            }else{
                d=d+1;//2
            }
        }
        if(sd!=so){
            v[0]=o;
            v[1]=d;
            v[2]=so;
            v[3]=sd;
        }else{
            v[0]=o;
            v[1]=d;
            v[2]=0;
            v[3]=0;
        }
        return v;
    }
    public double[][]crear_nueva_matriz(double m[][],int o,int d,double so,double sd,DefaultTableModel mo){
        double sobra=0;int i1=0,j1=0;
        double m1[][]=new double[o][d];
        System.out.println(sd+"   "+so);
        if(sd>so){
            sobra=sd-so;
            m1[o-2][d-1]=sobra;
            for(int i=0;i<o;i++){
                j1=0;
                if(i!=o-2){
                    for(int j=0;j<d;j++){
                        m1[i][j]=m[i1][j1];
                        j1++;
                    }i1++;
                }
            }
            
        }else{
            sobra=so-sd;
            m1[o-1][d-2]=sobra;
            for(int i=0;i<o;i++){
                j1=0;
                for(int j=0;j<d;j++){
                    if(j!=d-2){
                        m1[i][j]=m[i1][j1];
                        j1++;
                    }
                }
                i1++;
            }
        }
        
         mo.setRowCount(o);
        mo.setColumnCount(d);
        
        for(int i=0;i<o;i++){
            for(int j=0;j<d;j++){
                tabla1.setValueAt(m1[i][j], i, j);
            }
        }
        return m1;
    }
    public void operacion(double m1[][],int o,int d){
        double b[][]=new double[o][d];
        for(int i=0;i<o;i++){
            b[i][d-1]=m1[i][d-1];
        }
         for(int i=0;i<d;i++){
            b[o-1][i]=m1[o-1][i];
        }/*
         for(int i=0;i<o;i++){
             for(int j=0;j<d;j++){
             System.out.print(b[i][j]+" ");
             }System.out.println();
         }*/
        int pos=0;int c2=0;
        for(int i=0;i<o;i++){
            for(int j=pos;j<d;j++){
                if(b[i][d-1]==b[o-1][j]){
                    b[i][j]=b[i][d-1];
                    b[i][d-1]=0;
                    b[o-1][j]=0;
                    pos=j;c2=1;
                    break;
                }else{
                    if(b[i][d-1]<b[o-1][j]){
                             
                        b[o-1][j]=b[o-1][j]-b[i][d-1];
                        b[i][j]=b[i][d-1];
                        b[i][d-1]=0;
                        pos=j;
                        break;
                    }else{
                        b[i][d-1]=b[i][d-1]-b[o-1][j];
                        b[i][j]=b[o-1][j];
                        b[o-1][j]=0;
                    }
                    
                }
            }
            if(c2==1){break;}
        }
        DefaultTableModel model = (DefaultTableModel) tabla3.getModel();
        model.setRowCount(o);
        model.setColumnCount(d);
        double su=0;
        for(int i=0;i<o;i++){
            for(int j=0;j<d;j++){
             if(b[i][j]!=0){
                    
             tabla3.setValueAt("[ "+b[i][j]+" , "+m1[i][j]+" ]", i, j);
             su=su+b[i][j]*m1[i][j];
            }else{
             tabla3.setValueAt(" - ", i, j);
             }
            }
        }
        label.setText("Costo Total: "+su);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        demandaa = new javax.swing.JTextField();
        oferta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla1);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla3);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear tabla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Esquina Noroeste");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FILAS");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COLUMNAS");

        jLabel3.setText("Columnas");

        jLabel2.setText("Filas");

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 34, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(66, 66, 66))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(demandaa)
                                            .addComponent(oferta))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(135, 135, 135)
                                .addComponent(jLabel4)))
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(demandaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)))
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int d=Integer.parseInt(demandaa.getText());
        int o=Integer.parseInt(oferta.getText());
        double m[][]=new double[o][d];
        for(int i=0;i<o;i++){
            for(int j=0;j<d;j++){
                m[i][j]=Double.parseDouble(""+tabla1.getValueAt(i, j));
            }
        }
         DefaultTableModel modeles = (DefaultTableModel) tabla1.getModel();
        double v[]=comprobar(m,o,d);
        o=(int)(v[0]);
        d=(int)(v[1]);
        double so=0,sd=0;
        so=v[2];
        sd=v[3];
        //System.out.println(o+" "+d);
        if(so!=sd){
        double m2[][]=crear_nueva_matriz(m,o,d,so,sd,modeles);
        operacion(m2,o,d);
        }else{
        operacion(m,o,d);
        }
        /*
         for(int i=0;i<o;i++){
            for(int j=0;j<d;j++){
            System.out.print(m[i][j]+" ");
            }
         System.out.println();
         }*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeles = (DefaultTableModel) tabla1.getModel();
        int d=Integer.parseInt(demandaa.getText());
        int o=Integer.parseInt(oferta.getText());
        modeles.setRowCount(o);
        modeles.setColumnCount(d);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField demandaa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label;
    private javax.swing.JTextField oferta;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla3;
    // End of variables declaration//GEN-END:variables
}
